---
:workflow_id: spec_workflow
:name: Spec Workflow
:auto_queue: false
:actions:
  :inspect:
    :class: Workflow::Inspect
  :transcode_high:
    :class: Workflow::Transcode
    :prereqs:
      - :inspect
    :config:
      :params:
        :command_line: '-vf yadif=0:-1:1,scale=trunc(oh*dar/2)*2:720 -vcodec libx264 -preset fast -b 4M -maxrate 4M -bufsize 8M -refs 5 -me_method umh -bf 0 -subq 8 -threads 0 -r 30 -force_key_frames expr:gte(t,n_forced/2) -pix_fmt yuv420p -acodec libfaac -ab 256k -ar 48000'
  :transcode_medium:
    :class: Workflow::Transcode
    :prereqs:
      - :inspect
    :config:
      :params:
        :command_line: '-vf yadif=0:-1:1,scale=trunc(oh*dar/2)*2:480 -vcodec libx264 -preset fast -b 2M -maxrate 2M -bufsize 4M -refs 5 -me_method umh -bf 0 -subq 8 -threads 0 -r 30 -force_key_frames expr:gte(t,n_forced/2) -pix_fmt yuv420p -acodec libfaac -ab 192k -ar 48000'
  :transcode_low:
    :class: Workflow::Transcode
    :prereqs:
      - :inspect
    :config:
      :params:
        :command_line: '-vf yadif=0:-1:1,scale=trunc(oh*dar/2)*2:360 -vcodec libx264 -preset fast -b 1M -maxrate 1M -bufsize 2M -refs 5 -me_method umh -bf 0 -subq 8 -threads 0 -r 30 -force_key_frames expr:gte(t,n_forced/2) -pix_fmt yuv420p -acodec libfaac -ab 96k -ar 32000'
  :distribute:
    :class: Workflow::Copy
    :prereqs:
      - :transcode_high
      - :transcode_medium
      - :transcode_low
  :cleanup:
    :class: Workflow::Cleanup
    :prereqs:
      - :distribute
